schedtool: provide cross compile CC
CC is not properly defined, and hence, we get QA errors like the following:

ERROR: schedtool-dl-1.0-r0 do_package_qa: QA Issue: Architecture did not match (3 to 62) on work/core2-32-poky-linux/schedtool-dl/1.0-r0/packages-split/schedtool-dl-dbg/usr/bin/.debug/schedtool [arch]
ERROR: schedtool-dl-1.0-r0 do_package_qa: QA Issue: Architecture did not match (3 to 62) on work/core2-32-poky-linux/schedtool-dl/1.0-r0/packages-split/schedtool-dl/usr/bin/schedtool [arch]
WARNING: schedtool-dl-1.0-r0 do_package_qa: QA Issue: /usr/bin/schedtool contained in package schedtool-dl requires libc.so.6(GLIBC_2.4)(64bit),
but no providers found in RDEPENDS_schedtool-dl? [file-rdeps]
ERROR: schedtool-dl-1.0-r0 do_package_qa: QA run found fatal errors.  Please consider fixing them.
ERROR: schedtool-dl-1.0-r0 do_package_qa: Function failed: do_package_qa

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>